{% set name = "wcurl" %}
{% set version = "2025.04.20" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/curl/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c40ccf365febca9115611db271b2d6705728fc7efb297df3f2eba70d3a97fa03

build:
  number: 0
  noarch: generic

requirements:
  run:
    - curl >=7.83.0
    - __unix   # [unix]
    - __win    # [win]
    - m2-bash  # [win]

test:
  commands:
    - wcurl --help
    - wcurl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE.txt
    - test -f LICENSE.txt              # [unix]
    - if not exist LICENSE.txt exit 1  # [win]

about:
  home: https://curl.se/wcurl
  license: curl
  license_family: MIT
  license_file: LICENSE
  summary: A simple wrapper around curl to easily download files
  description: |
    wcurl is a command line tool which lets you download URLs without having to
    remember any parameters.
  doc_url: https://curl.se/wcurl
  dev_url: https://github.com/curl/wcurl

extra:
  recipe-maintainers:
    - apcamargo
